In [1]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import sklearn
from torch.utils.data import DataLoader
from sklearn.model_selection import train_test_split
from torch import optim

In [3]:
df = pd.read_json(r'Dataset\VeReMi_0_3600_2022-9-11_12.51.1\VeReMi_0_3600_2022-9-11_12_51_1\traceGroundTruthJSON-0.json',lines=True)

In [4]:
df.head()

type    sendTime  sender  senderPseudo  messageID  \
0     4  240.602763       9          1092       4184   
1     4  241.602763       9          1092       4194   
2     4  242.602763       9          1092       4204   
3     4  243.602763       9          1092       4214   
4     4  244.602763       9          1092       4224   

                                             pos  \
0    [266.1342377193001, 41.31755030776682, 0.0]   
1   [266.06130476311273, 43.37327132906824, 0.0]   
2  [265.50620000532376, 47.479615917740944, 0.0]   
3    [264.8798230282204, 53.81269421777557, 0.0]   
4   [263.74132084628656, 62.04745136461824, 0.0]   

                                     pos_noise  \
0  [4.534752768029631, 4.549525298598843, 0.0]   
1  [4.476469413385379, 4.331702683063567, 0.0]   
2  [4.642016156453815, 4.406704772182185, 0.0]   
3   [4.46289078603543, 4.600132676334774, 0.0]   
4  [4.359550875382791, 4.449767087397457, 0.0]   

                                               spd  \
0  [-0.08087719292206601, 0.7826628559043071, 0.0]   
1     [-0.307226018249808, 2.973074697703729, 0.0]   
2     [-0.522133162849577, 5.052698244401898, 0.0]   
3     [-0.7501579494382471, 7.25934146781901, 0.0]   
4     [-1.196011717133152, 9.262387108898814, 0.0]   

                                           spd_noise  \
0  [5.8479561322000003e-05, -0.000565907804593, 0.0]   
1  [0.00022214435466300002, -0.002149695059419, 0.0]   
2  [0.00037753164498000003, -0.003653380763227, 0.0]   
3   [0.0005424091366300001, -0.005248903322175, 0.0]   
4    [0.000864806049117, -0.006697196551177001, 0.0]   

                                              acl  \
0     [-0.264399876770306, 2.55929226383305, 0.0]   
1  [-0.16867421025649001, 1.632928207206669, 0.0]   
2    [-0.250340680719852, 2.423187784894591, 0.0]   
3  [-0.15859373985413902, 1.535395525905717, 0.0]   
4    [-0.323323397706463, 2.504311894356131, 0.0]   

                                           acl_noise  \
0        [0.000781535042957, 0.000157147677041, 0.0]   
1  [0.00016366479334100001, 0.0015837872548250002...   
2  [0.00015538729031600002, 0.0015036857038070001...   
3        [0.000164877491649, 0.001595522558947, 0.0]   
4   [0.00032239691248600003, 0.001448293229002, 0.0]   

                                               hed  \
0  [-0.10279023863398801, 0.9947030546055271, 0.0]   
1     [-0.102682182286077, 0.994714214958733, 0.0]   
2   [-0.10254626897553601, 0.994728235609705, 0.0]   
3  [-0.10231333056359201, 0.9947522216054531, 0.0]   
4  [-0.12733117487307702, 0.9918602582548821, 0.0]   

                                       hed_noise  
0   [0.34491692230051, 0.31638175763944104, 0.0]  
1  [0.352813203036476, 0.25414594164242404, 0.0]  
2  [0.360477346594304, 0.20642682168206902, 0.0]  
3    [0.368791704558564, 0.165551455629279, 0.0]  
4  [0.38560754428035204, 0.135501165937049, 0.0]

In [5]:
df1 = df[['pos','spd']]

In [6]:
df1.head()

pos  \
0    [266.1342377193001, 41.31755030776682, 0.0]   
1   [266.06130476311273, 43.37327132906824, 0.0]   
2  [265.50620000532376, 47.479615917740944, 0.0]   
3    [264.8798230282204, 53.81269421777557, 0.0]   
4   [263.74132084628656, 62.04745136461824, 0.0]   

                                               spd  
0  [-0.08087719292206601, 0.7826628559043071, 0.0]  
1     [-0.307226018249808, 2.973074697703729, 0.0]  
2     [-0.522133162849577, 5.052698244401898, 0.0]  
3     [-0.7501579494382471, 7.25934146781901, 0.0]  
4     [-1.196011717133152, 9.262387108898814, 0.0]

In [6]:
split = pd.DataFrame(df1['pos'].to_list(), columns = ['posX', 'posY','posZ'])

In [7]:
split.head()

posX       posY  posZ
0  266.134238  41.317550   0.0
1  266.061305  43.373271   0.0
2  265.506200  47.479616   0.0
3  264.879823  53.812694   0.0
4  263.741321  62.047451   0.0

In [8]:
split = split.drop('posZ',axis=1)

In [9]:
df1 = pd.concat([df1, split], axis=1) 

In [10]:
df1.head()

pos  \
0    [266.1342377193001, 41.31755030776682, 0.0]   
1   [266.06130476311273, 43.37327132906824, 0.0]   
2  [265.50620000532376, 47.479615917740944, 0.0]   
3    [264.8798230282204, 53.81269421777557, 0.0]   
4   [263.74132084628656, 62.04745136461824, 0.0]   

                                               spd        posX       posY  
0  [-0.08087719292206601, 0.7826628559043071, 0.0]  266.134238  41.317550  
1     [-0.307226018249808, 2.973074697703729, 0.0]  266.061305  43.373271  
2     [-0.522133162849577, 5.052698244401898, 0.0]  265.506200  47.479616  
3     [-0.7501579494382471, 7.25934146781901, 0.0]  264.879823  53.812694  
4     [-1.196011717133152, 9.262387108898814, 0.0]  263.741321  62.047451

In [11]:
df1 = df1.drop('pos',axis=1)

In [12]:
split = pd.DataFrame(df1['spd'].to_list(), columns = ['spdX', 'spdY','spdZ'])

In [13]:
split = split.drop('spdZ',axis=1)

In [14]:
split.head()

spdX      spdY
0 -0.080877  0.782663
1 -0.307226  2.973075
2 -0.522133  5.052698
3 -0.750158  7.259341
4 -1.196012  9.262387

In [15]:
df1 = pd.concat([df1, split], axis=1) 

In [16]:
df1.head()

spd        posX       posY  \
0  [-0.08087719292206601, 0.7826628559043071, 0.0]  266.134238  41.317550   
1     [-0.307226018249808, 2.973074697703729, 0.0]  266.061305  43.373271   
2     [-0.522133162849577, 5.052698244401898, 0.0]  265.506200  47.479616   
3     [-0.7501579494382471, 7.25934146781901, 0.0]  264.879823  53.812694   
4     [-1.196011717133152, 9.262387108898814, 0.0]  263.741321  62.047451   

       spdX      spdY  
0 -0.080877  0.782663  
1 -0.307226  2.973075  
2 -0.522133  5.052698  
3 -0.750158  7.259341  
4 -1.196012  9.262387

In [17]:
df1 = df1.drop('spd',axis=1)

In [18]:
df1.head()

posX       posY      spdX      spdY
0  266.134238  41.317550 -0.080877  0.782663
1  266.061305  43.373271 -0.307226  2.973075
2  265.506200  47.479616 -0.522133  5.052698
3  264.879823  53.812694 -0.750158  7.259341
4  263.741321  62.047451 -1.196012  9.262387

In [19]:
df1

posX        posY      spdX      spdY
0     266.134238   41.317550 -0.080877  0.782663
1     266.061305   43.373271 -0.307226  2.973075
2     265.506200   47.479616 -0.522133  5.052698
3     264.879823   53.812694 -0.750158  7.259341
4     263.741321   62.047451 -1.196012  9.262387
...          ...         ...       ...       ...
5021  139.526900  876.928567  0.001691  0.001691
5022  139.749557  876.918451  0.001691  0.001691
5023  139.412345  878.207028 -0.296062  2.253724
5024  138.107917  881.136414 -1.281437  3.882940
5025  134.008147  882.956575 -4.211086  1.818290

[5026 rows x 4 columns]

In [20]:
mini = min(df1['posX'].min(),df1['posY'].min())
print(mini)
maxi = max(df1['posX'].max(),df1['posY'].max())
print(maxi)

28.980277651947247
1395.2828741038516


In [21]:
df1['posX'] = (df1['posX'] - mini)/(maxi - mini)

In [22]:
df1['posY'] = (df1['posY'] - mini)/(maxi - mini)

In [23]:
mini = min(df1['spdX'].min(),df1['spdY'].min())
print(mini)
maxi = max(df1['spdX'].max(),df1['spdY'].max())
print(maxi)

-17.411613086781816
16.282034131930875


In [24]:
df1['spdX'] = ((df1['spdX'] - mini)/(maxi - mini))*2 -1 

In [25]:
df1['spdY'] = ((df1['spdY'] - mini)/(maxi - mini))*2 -1 

In [26]:
df1.head()

posX      posY      spdX      spdY
0  0.173574  0.009030  0.028724  0.079983
1  0.173520  0.010534  0.015289  0.210002
2  0.173114  0.013540  0.002532  0.333445
3  0.172655  0.018175 -0.011003  0.464428
4  0.171822  0.024202 -0.037468  0.583325

In [27]:
input_comb = []

for i in range(len(df)):
    if i%20==0 and len(df)-i>20:
        curr = []
        for j in range(20):
            curr.append(np.array(df1.iloc[i+j]))
        input_comb.append(curr)

input_comb = np.array(input_comb)
input_comb = torch.from_numpy(input_comb)

In [28]:
input_comb

tensor([[[ 0.1736,  0.0090,  0.0287,  0.0800],
         [ 0.1735,  0.0105,  0.0153,  0.2100],
         [ 0.1731,  0.0135,  0.0025,  0.3334],
         ...,
         [ 0.1511,  0.1560, -0.0943,  0.8836],
         [ 0.1495,  0.1665, -0.0942,  0.8830],
         [ 0.1479,  0.1770, -0.0947,  0.8864]],

        [[ 0.1465,  0.1875, -0.0946,  0.8860],
         [ 0.1450,  0.1980, -0.0947,  0.8862],
         [ 0.1433,  0.2085, -0.0947,  0.8865],
         ...,
         [ 0.1178,  0.3644, -0.0645,  0.6844],
         [ 0.1168,  0.3707, -0.0247,  0.4202],
         [ 0.1165,  0.3737,  0.0150,  0.1566]],

        [[ 0.1165,  0.3739,  0.0336,  0.0336],
         [ 0.1165,  0.3739,  0.0336,  0.0336],
         [ 0.1165,  0.3739,  0.0336,  0.0336],
         ...,
         [ 0.1167,  0.3739,  0.0336,  0.0336],
         [ 0.1169,  0.3739,  0.0336,  0.0336],
         [ 0.1169,  0.3739,  0.0336,  0.0336]],

        ...,

        [[ 0.2964,  0.3866, -0.5635, -0.4651],
         [ 0.2889,  0.3804, -0.5754, -0.4582]

In [29]:
class Dataset(torch.utils.data.Dataset):
#   'Characterizes a dataset for PyTorch'
    def __init__(self, list_IDs, labels):
#         'Initialization'
        self.labels = labels
        self.list_IDs = list_IDs
        
    def __len__(self):
#         'Denotes the total number of samples'
        return len(self.list_IDs)

    def __getitem__(self, index):
#         'Generates one sample of data'
        # Select sample
        ID = self.list_IDs[index]

        # Load data and get label
        X = torch.load('data/' + ID + '.pt')
        y = self.labels[ID]

        return X, y

In [30]:
labels = torch.zeros(len(input_comb))
labels.shape

torch.Size([251])

In [31]:
X_train, X_rem, y_train, y_rem = train_test_split(input_comb,labels, train_size=0.85)
X_valid, X_test, y_valid, y_test = train_test_split(X_rem,y_rem, test_size=0.5)

In [32]:
training_data = Dataset(X_train,y_train)
validation_data = Dataset(X_valid,y_valid)
test_data = Dataset(X_test,y_test)

In [33]:
train_dataloader = DataLoader(training_data, batch_size=32, shuffle=True)
val_dataloader = DataLoader(training_data, batch_size=32, shuffle=True)
test_dataloader = DataLoader(test_data, batch_size=32, shuffle=True)

In [34]:
class CNN_LSTM(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = nn.Conv1d(in_channels=20, out_channels=20, kernel_size=3)
        
        self.lstm1 = nn.LSTM(input_size=2,hidden_size=2,num_layers=256)
        self.lstm2 = nn.LSTM(input_size=2,hidden_size=2,num_layers=256)
        self.lstm3 = nn.LSTM(input_size=2,hidden_size=2,num_layers=256)
        self.lstm4 = nn.LSTM(input_size=2,hidden_size=2,num_layers=256)
        
        self.lin1 = nn.Linear(2,1)
        self.lin2 = nn.Linear(4,2)
        
    def forward(self,x):
        h0_1 = torch.randn(256,2)
        c0_1 = torch.randn(256,2)
        h0_2 = torch.randn(256,2)
        c0_2 = torch.randn(256,2)
        h0_3 = torch.randn(256,2)
        c0_3 = torch.randn(256,2)
        h0_4 = torch.randn(256,2)
        c0_4 = torch.randn(256,2)
        
        
        x = self.conv(x)
        
        o1, _ = self.lstm1(x,(h0_1,c0_1))
        o2, _ = self.lstm2(x,(h0_2,c0_2))
        o3, _ = self.lstm3(x,(h0_3,c0_3))
        o4, _ = self.lstm4(x,(h0_4,c0_4))
        
        out1 = self.lin1(o1)
        out2 = self.lin1(o2)
        out3 = self.lin1(o3)
        out4 = self.lin1(o4)
        
        out_comb = torch.stack((out1,out2,out3,out4),dim=1)
        out_comb = out_comb.squeeze()
        
        out_final = self.lin2(out_comb)

        
        return out_final

In [35]:
input = input_comb[0]
# input = torch.randn(20,4)
print(input)

tensor([[ 0.1736,  0.0090,  0.0287,  0.0800],
        [ 0.1735,  0.0105,  0.0153,  0.2100],
        [ 0.1731,  0.0135,  0.0025,  0.3334],
        [ 0.1727,  0.0182, -0.0110,  0.4644],
        [ 0.1718,  0.0242, -0.0375,  0.5833],
        [ 0.1707,  0.0318, -0.0705,  0.7057],
        [ 0.1695,  0.0410, -0.0843,  0.8392],
        [ 0.1678,  0.0513, -0.1148,  0.8814],
        [ 0.1663,  0.0618, -0.1073,  0.8862],
        [ 0.1645,  0.0723, -0.1017,  0.8790],
        [ 0.1629,  0.0827, -0.1092,  0.8831],
        [ 0.1610,  0.0932, -0.1198,  0.8831],
        [ 0.1591,  0.1036, -0.1069,  0.8851],
        [ 0.1573,  0.1141, -0.1070,  0.8862],
        [ 0.1557,  0.1246, -0.0895,  0.8860],
        [ 0.1542,  0.1351, -0.0915,  0.8809],
        [ 0.1527,  0.1455, -0.0925,  0.8882],
        [ 0.1511,  0.1560, -0.0943,  0.8836],
        [ 0.1495,  0.1665, -0.0942,  0.8830],
        [ 0.1479,  0.1770, -0.0947,  0.8864]], dtype=torch.float64)


In [36]:
model = CNN_LSTM()

In [37]:
output = model(input.float())

In [38]:
output

tensor([[ 0.2136, -0.1846],
        [ 0.2261, -0.1780],
        [ 0.2063, -0.1810],
        [ 0.1945, -0.1888],
        [ 0.1867, -0.1973],
        [ 0.1811, -0.2050],
        [ 0.1770, -0.2115],
        [ 0.1739, -0.2166],
        [ 0.1716, -0.2205],
        [ 0.1699, -0.2234],
        [ 0.1687, -0.2255],
        [ 0.1678, -0.2270],
        [ 0.1672, -0.2280],
        [ 0.1668, -0.2287],
        [ 0.1665, -0.2292],
        [ 0.1663, -0.2295],
        [ 0.1662, -0.2297],
        [ 0.1661, -0.2298],
        [ 0.1661, -0.2299],
        [ 0.1661, -0.2299]], grad_fn=<AddmmBackward0>)

In [46]:
criterion = nn.L1Loss()
# optimizer = optim.SGD(model.parameters(), lr=0.001, momentum=0.9)
optimizer = optim.Adam(model.parameters(),lr=0.0003)

In [40]:
y_train

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
def thresholding_algorithm(X, X_dash, Y, iterations=100, starting_threshold=0.005, precision=0.1):
    device = X.device # get the device of the input tensors
    N = iterations
    Accuracy = torch.zeros(N, device=device)
    threshold = torch.linspace(starting_threshold, starting_threshold + (N-1)*precision, N, device=device)
    st = starting_threshold
    pre = precision
    m = int(torch.ceil(torch.log10(torch.Tensor([N]).to(device))))
    for l in range(m):
        for i in range(N):
            Accuracy[i] = 0
            threshold[i] = st + (i/pre)
            for j in range(len(X)):
                mae = torch.mean(torch.abs(X[j]-X_dash[j])).item()
                if (mae < threshold[i] and Y[j] == 0) or (mae > threshold[i] and Y[j] != 0):
                    Accuracy[i] += 1/len(X)
        threshold_max = st + (torch.argmax(Accuracy))/pre
        en = st + ((torch.argmax(Accuracy) + 1)/pre)
        st = st + ((torch.argmax(Accuracy) - 1)/pre)
        pre *= 10
        N = int((en - st) * pre)
        threshold = torch.linspace(st, en, N, device=device)
    return threshold_max,Accuracy.max()

In [42]:
thresholding_algorithm(input_comb[0][:,:2],output,torch.zeros(20))

(tensor(1.0050), tensor(1.0000))

In [43]:
torch.mean(input_comb[0][0,:2] - output[0]).item()

0.07680068635354939

In [44]:
X_train.shape
output_train = torch.zeros(213,20,2)